# Generated by Django 5.1.7 on 2025-03-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="reset_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reset_token",
        ),
    ]
